/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Dipjyoti' at '8/12/16 11:47 PM' with Gradle 2.14
 *
 * @author Dipjyoti, @date 8/12/16 11:47 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
